# .github/workflows/release.yml

name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # 触发规则，匹配类似 v1.0.0, v2024.12.31 的标签

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.25.0'

      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -A x64 .. -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
          cmake --build . --config ${{ env.BUILD_TYPE }}

      - name: Collect Artifacts
        run: |
          cd build
          powershell Compress-Archive -Path .\Release\* -DestinationPath ../release.zip

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: "version ${{ github.ref_name }}"
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: YourProject-v${{ github.ref_name }}.zip
          asset_content_type: application/zip
